//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_satis
    {
        public int satisid { get; set; }
        public Nullable<decimal> satisfiyat { get; set; }
        public Nullable<int> satisadet { get; set; }
        public Nullable<System.DateTime> satistarih { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> musteri { get; set; }
    
        public virtual tbl_musteri tbl_musteri { get; set; }
        public virtual tbl_urun tbl_urun { get; set; }
    }
}
